# Generated by Django 3.0.4 on 2020-03-31 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='Images',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
